export { default as MunimAccountShots } from "./munim account.webp"
export { default as LabGrownShots } from "./labgrown.webp"
export { default as BridiShots } from "./BridI.webp"
export { default as CareMagnusShots  } from "./CareMagnus- Hospital.webp"
export { default as BoatBookingShots } from "./Boat Booking.webp"
export { default as RoccaShots } from "./RoccaBox.webp"